# Project: de_tham_khao_cau2_chia_de_tri
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = cau2.o
LINKOBJ  = cau2.o
LIBS     = -L"D:/Edit/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib32" -static-libgcc -m32
INCS     = -I"D:/Edit/Dev-Cpp/TDM-GCC-64/include" -I"D:/Edit/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Edit/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/Edit/Dev-Cpp/TDM-GCC-64/include" -I"D:/Edit/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Edit/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Edit/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = Cau2_chia_de_tri.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
DEL      = D:\Edit\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

cau2.o: cau2.cpp
	$(CPP) -c cau2.cpp -o cau2.o $(CXXFLAGS)
