# Project: Mang1Chieu
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Mang1Chieu.o
LINKOBJ  = Mang1Chieu.o
LIBS     = -L"D:/Edit/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib32" -static-libgcc -m32
INCS     = -I"D:/Edit/Dev-Cpp/TDM-GCC-64/include" -I"D:/Edit/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Edit/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/Edit/Dev-Cpp/TDM-GCC-64/include" -I"D:/Edit/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Edit/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Edit/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = Mang1Chieu.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
DEL      = D:\Edit\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Mang1Chieu.o: Mang1Chieu.cpp
	$(CPP) -c Mang1Chieu.cpp -o Mang1Chieu.o $(CXXFLAGS)
